version: '3.8'
services:
  web:
    build: .
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
